// Generated by CoffeeScript 1.10.0
(function() {
  var commander, config, download, fs, https, i, image, install, len, ref, request, resolutions, user;

  https = require('https');

  fs = require('fs');

  request = require('request');

  commander = require('commander');

  user = require('./pickselacc.json');

  config = require('./picksel.json');

  resolutions = ['previewURL', 'webformatURL', 'largeImageURL', 'fullHDURL', 'imageURL', 'vectorURL'];

  download = function(id, resolution, destination) {
    var options, url;
    url = 'https://pixabay.com/api/?key=' + user.apiKey + (resolution > 1 ? '&response_group=high_resolution' : '') + '&id=' + id;
    options = {
      url: url,
      json: true
    };
    return request(options, function(error, response, body) {
      var file, req;
      file = fs.createWriteStream(destination);
      return req = https.get(body.hits[0][resolutions[resolution]], function(res) {
        return res.pipe(file);
      });
    });
  };

  install = function(image) {
    var path;
    path = './' + config.directory + '/' + image.destination;
    return download(image.id, image.resolution, path);
  };

  commander.version('0.0.1').option('-i, --install', 'download all images specified in picksel.json').parse(process.argv);

  if (commander.install) {
    ref = config.images;
    for (i = 0, len = ref.length; i < len; i++) {
      image = ref[i];
      install(image);
    }
  }

}).call(this);
